/** Every GLB in public/models (built by art/blender/build.py). */
export const MODEL_NAMES = [
  'developer',
  'token',
  'boulder',
  // low
  'jersey_barrier',
  'cone_cluster',
  'barrel_row',
  'brick_pallet',
  'pipe_stack',
  'sandbag_wall',
  'wheelbarrow',
  'toolbox_crate',
  'rock_pile',
  // overhead
  'height_gantry',
  'vent_duct',
  'cable_tray',
  'scaffold_beam',
  'pipe_bundle',
  'girder',
  // blocks and moving
  'excavator',
  'road_roller',
  'site_cabin',
  'mine_cart',
  'segment_stack',
  'drill_rig',
  'bulldozer',
  'scissor_lift',
  'dump_truck',
  'mixer_truck',
  'container',
  'container_platform',
  'ramp',
  'rolling_pipe',
  'crane_load',
  'sweep_arm',
  // pickups
  'laptop',
  'energy_can',
  'coffee_cup',
  'ai_spark',
  'boots',
  'mystery_box',
  // scenery
  'tower_crane',
  'building_frame',
  'floodlight_tower',
  'sign_post',
  'billboard',
  'cone',
  'pipe_rack',
  'tbm_cutterhead',
  'tunnel_ring',
  'scaffold_wall',
  'rock_wall',
  'blast_sign',
  'bridge_truss',
  'site_gate',
  'tunnel_portal',
  'skyline',
  'rubber_duck',
] as const;
